
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
scene: !include scenes.yaml

# Helpers
group: !include helpers/group.yaml

# Auto Off Helpers
input_number: !include helpers/auto_off/input_number.yaml
input_select: !include helpers/auto_off/input_select.yaml

# Guardian Helpers
input_boolean: !include helpers/guardian/input_boolean.yaml
input_datetime: !include helpers/guardian/input_datetime.yaml
input_number: !include helpers/guardian/input_number.yaml
input_select: !include helpers/guardian/input_select.yaml
timer: !include helpers/guardian/timer.yaml



notify:
  - name: email_sam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: 2020sentinel@gmail.com
    password: !secret gmail_app_password
    sender: 2020sentinel@gmail.com
    recipient:
      - 7050592@gmail.com

  - name: sms_sam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: 2020sentinel@gmail.com
    password: !secret gmail_app_password
    sender: 2020sentinel@gmail.com
    recipient:
      - 5102465504@vtext.com
