
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# automation: !include automations.yaml


automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
scene: !include scenes.yaml

input_number: !include helpers/input_number.yaml
input_select: !include helpers/input_select.yaml
input_boolean: !include helpers/input_boolean.yaml
group: !include helpers/group.yaml
input_datetime: !include helpers/input_datetime.yaml
timer: !include helpers/timer.yaml

# homeassistant:
#   packages: !include_dir_named packages

notify:
  - name: email_sam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: 2020sentinel@gmail.com
    password: !secret gmail_app_password
    sender: 2020sentinel@gmail.com
    recipient:
      - 7050592@gmail.com

  - name: sms_sam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: 2020sentinel@gmail.com
    password: !secret gmail_app_password
    sender: 2020sentinel@gmail.com
    recipient:
      - 5102465504@vtext.com
