
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
scene: !include scenes.yaml

# Helpers
group: !include helpers/group.yaml
input_number: !include_dir_merge_named helpers/input_number
input_select: !include_dir_merge_named helpers/input_select
input_boolean: !include_dir_merge_named helpers/input_boolean
input_datetime: !include_dir_merge_named helpers/input_datetime
input_text: !include_dir_merge_named helpers/input_text
timer: !include_dir_merge_named helpers/timer



notify:
  - name: email_sam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: 2020sentinel@gmail.com
    password: !secret gmail_app_password
    sender: 2020sentinel@gmail.com
    recipient:
      - 7050592@gmail.com

  - name: sms_sam
    platform: smtp
    server: smtp.gmail.com
    port: 587
    encryption: starttls
    username: 2020sentinel@gmail.com
    password: !secret gmail_app_password
    sender: 2020sentinel@gmail.com
    recipient:
      - 5102465504@vtext.com
