
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts

# script: !include scripts.yaml
scene: !include scenes.yaml

input_number: !include helpers/input_number.yaml
input_select: !include helpers/input_select.yaml
input_boolean: !include helpers/input_boolean.yaml
group: !include helpers/group.yaml
input_datetime: !include helpers/input_datetime.yaml
timer: !include helpers/timer.yaml

# homeassistant:
#   packages: !include_dir_named packages
